package com.eignex.klause.util

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class PermutationGroupTest {

    private fun compose(a: IntArray, b: IntArray) = IntArray(a.size) { a[b[it]] }

    /** The full group generated by [gens] over `[0,n)`, by closing under composition (small n only). */
    private fun closure(gens: List<IntArray>, n: Int): Set<List<Int>> {
        val all = HashSet<List<Int>>()
        all.add((0 until n).toList())
        var frontier = all.toList()
        while (frontier.isNotEmpty()) {
            val next = ArrayList<List<Int>>()
            for (p in frontier) {
                val pa = p.toIntArray()
                for (g in gens) {
                    val c = compose(g, pa).toList()
                    if (all.add(c)) next.add(c)
                }
            }
            frontier = next
        }
        return all
    }

    @Test
    fun `orbit reaches every point of a transitive group`() {
        val cycle = intArrayOf(1, 2, 0) // (0 1 2)
        assertEquals(setOf(0, 1, 2), PermutationGroup.orbit(listOf(cycle), 0))
    }

    @Test
    fun `orbit is the singleton for a fixed point`() {
        val swap01 = intArrayOf(1, 0, 2) // (0 1), fixes 2
        assertEquals(setOf(2), PermutationGroup.orbit(listOf(swap01), 2))
    }

    @Test
    fun `strong generators are genuine group elements`() {
        // S3 from two transpositions; every Schreier generator must be one of the 6 group elements.
        val s3 = listOf(intArrayOf(1, 0, 2), intArrayOf(0, 2, 1))
        val members = closure(s3, 3)
        val strong = PermutationGroup.strongGenerators(s3, 3, cap = 64)
        for (g in strong) {
            assertEquals(3, g.size)
            assertTrue(g.toList() in members, "strong generator ${g.toList()} is not a group element")
            assertEquals((0..2).toSet(), g.toSet(), "not a permutation: ${g.toList()}")
        }
        assertTrue(strong.isNotEmpty())
    }

    @Test
    fun `strong generators respect the cap`() {
        val s4 = listOf(intArrayOf(1, 0, 2, 3), intArrayOf(0, 2, 1, 3), intArrayOf(0, 1, 3, 2))
        val strong = PermutationGroup.strongGenerators(s4, 4, cap = 5)
        assertTrue(strong.size <= 5, "cap not respected: ${strong.size}")
    }
}
